import { FileSignature } from 'lucide-react';
import DashboardCard from '../shared/DashboardCard';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';
import { format } from 'date-fns';

interface CheckRequisition {
    id: number;
    requisition_number: string;
    requisition_status: string;
    php_amount: number;
    request_date: string;
    payee_name: string;
    invoice_count: number;
    generator_name: string;
    days_pending: number;
}

interface CRApprovalWidgetProps {
    data: CheckRequisition[];
}

export default function CRApprovalWidget({ data }: CRApprovalWidgetProps) {
    const formatCurrency = (value: number) => {
        return new Intl.NumberFormat('en-PH', {
            style: 'currency',
            currency: 'PHP',
            minimumFractionDigits: 0,
        }).format(value);
    };

    const getUrgencyBadge = (daysPending: number) => {
        if (daysPending > 7) {
            return { variant: 'destructive' as const, label: 'Urgent' };
        } else if (daysPending > 3) {
            return { variant: 'secondary' as const, label: 'High Priority' };
        }
        return { variant: 'outline' as const, label: 'Normal' };
    };

    const isEmpty = data.length === 0;
    const totalAmount = data.reduce((sum, cr) => sum + cr.php_amount, 0);

    return (
        <DashboardCard
            title="CR Approval Queue"
            description={`${data.length} check requisition(s) pending approval • Total: ${formatCurrency(totalAmount)}`}
            icon={FileSignature}
        >
            {isEmpty ? (
                <div className="flex items-center justify-center h-64 text-muted-foreground">
                    <p className="text-sm">No check requisitions pending approval</p>
                </div>
            ) : (
                <ScrollArea className="h-[400px]">
                    <div className="space-y-3">
                        {data.map((cr) => (
                            <div
                                key={cr.id}
                                className="border rounded-lg p-4 hover:bg-accent/50 transition-colors"
                            >
                                <div className="flex items-start justify-between mb-2">
                                    <div className="flex-1">
                                        <div className="flex items-center gap-2 mb-1">
                                            <h4 className="font-semibold text-sm">{cr.requisition_number}</h4>
                                            <Badge variant={getUrgencyBadge(cr.days_pending).variant} className="text-xs">
                                                {getUrgencyBadge(cr.days_pending).label}
                                            </Badge>
                                        </div>
                                        <p className="text-sm text-muted-foreground mb-1">{cr.payee_name}</p>
                                        <p className="text-xs text-muted-foreground">
                                            Generated by: {cr.generator_name}
                                        </p>
                                    </div>
                                    <div className="text-right">
                                        <p className="font-semibold">{formatCurrency(cr.php_amount)}</p>
                                        <p className="text-xs text-muted-foreground">
                                            {cr.invoice_count} invoice{cr.invoice_count !== 1 ? 's' : ''}
                                        </p>
                                    </div>
                                </div>
                                <div className="flex items-center justify-between text-xs text-muted-foreground">
                                    <span>
                                        Pending: {cr.days_pending} day{cr.days_pending !== 1 ? 's' : ''}
                                    </span>
                                    <span>
                                        Requested: {format(new Date(cr.request_date), 'MMM dd, yyyy')}
                                    </span>
                                </div>
                            </div>
                        ))}
                    </div>
                </ScrollArea>
            )}
        </DashboardCard>
    );
}
